@startuml

abstract class Client {
  #client
  ==
  getValue(): number
}

interface Target {
  getValue(): number
  ..
}

Target <-- Client: 关联

abstract class BaseAdapter {
  getTargetValue(): number
  ..
}

class Adapter extends BaseAdapter implements Target {
  #value: number
  --
  #adapter: BaseAdapter
  ==
  @Override
  getValue(): number
}


@enduml
