@startmindmap
* Deno
** Functions
*** Deno
**** Deno.chdir
**** Deno.chmod
**** Deno.chown
**** Deno.close
**** Deno.connect
**** Deno.copy
**** Deno.create
**** Deno.cwd
**** Deno.execPath
**** Deno.inspect
**** Deno.isatty
**** Deno.iter
**** Deno.listen
**** Deno.lstat
**** Deno.makeTempDir
**** Deno.makeTempFile
**** Deno.mkdir
**** Deno.open
**** Deno.read
**** Deno.readDir
**** Deno.readFile
**** Deno.readLink
**** Deno.readTextFile
**** Deno.realPath
**** Deno.remove
**** Deno.rename
**** Deno.resources
**** Deno.run
**** Deno.seek
**** Deno.truncate
**** Deno.watchFs
**** Deno.write
**** Deno.writeFile
**** Deno.writeTextFile

*** addEventListener
*** dispatchEvent
*** removeEventListener
*** atob
*** btoa
*** queueMicrotask
*** setTimeout
*** setInterval
*** fetch
@endmindmap
